dist: xenial
language: python
python: "3.7"

install:
  - pip install --upgrade pip
  - pip install -U -r requirements.txt
  - pip install pep8 pytest-pep8 pytest-xdist
  - pip install python-coveralls pytest-cov
  - pip install tensorflow==1.13.1
  - pip install gpflow==1.3
  - pip install pytest-forked
  - ./setup.sh
  - python setup.py build_ext --inplace
  - pip install -e .

script:
  - pytest --cov=sdcit --pep8

after_success:
  - coveralls